version = 1

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
  skip_doc_coverage = ["module", "magic", "init"]
  type_checker = "mypy"

[[analyzers]]
name = "test-coverage"
enabled = true

test_patterns = [
  "tests/**",
  "test_*.py"
]